### ISSUE TITLE
how to specify a certain script

### ISSUE THREAD

**Issue by nicolas931010** [Openscapes/demo#9]
@nt246 @joyceongjl

**Comment by nt246** [comment]
That's a really good question, let's ask @jules32

**Comment by joyceongjl** [comment]
=) how do i put in an emoji

**Comment by jules32** [comment]
Super important question @joyceongjl: Here is the [Complete list of github markdown emoji markup](https://gist.github.com/rxaviers/7360908)!

:relieved: :star2: :musical_note:

**Comment by jules32** [comment]
@ nicolas931010 to specify a certain script you can link to it using `[](url)` in markdown like this: [demo_script.R](https://github.com/Openscapes/demo/blob/gh-pages/demo_script.R). 

But, if you wanted to actually call this script from R, you can do that too. First, go to the script on Github:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/5891909/54772801-69f7d180-4bc5-11e9-938f-65c9c1b64dc3.png">

And click the "Raw" button on the right. This will take you to the plain text version and the url will begin with "https://raw.githubusercontent.com/" instead of "github.com":

<img width="734" alt="image" src="https://user-images.githubusercontent.com/5891909/54772890-9c093380-4bc5-11e9-9581-4f8f7537dc7b.png">

And it is this url that you can use to read in a script directly from R! So locally you could write

```r
# My awesome analysis

# load important script
source("https://raw.githubusercontent.com/Openscapes/demo/gh-pages/demo_script.R")

# continued analysis...
```

And now you'll have that x variable loaded locally. 

Give it a try!
